name: Test
on: [pull_request]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Proofread PR
        uses: ./
        id: proofread
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ntsd/auto-request-changes-action@v2
        if: ${{ failure() }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: hmarr/auto-approve-action@v2
        if: ${{ success() }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
