name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Proofread PR
        uses: ./
        id: proofread
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
